[package]
name = "mini-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "mini_core"
crate-type = ["staticlib"]

[dependencies]
cef.workspace = true
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSApplication", "NSEvent", "NSResponder"] }
